# SPDX-License-Identifier: Apache-2.0
"""Partner-card renderers (ADR-009 §Decision as amended 2026-07-05; ADR-027 §Consequences).

Renders ``docs/reference/partners/<set_id>-v<N>/`` — one card per set
member plus a per-set roster index — from the set registry
(:mod:`chamber.partners.sets`) and the committed fingerprint archive
(``spikes/results/partner-fingerprints/<set_id>-v<N>/fingerprints.json``),
so the public partner surface cannot drift from code or evidence. The
``scripts/render_partner_cards.py`` wrapper does the file IO and the
``--check`` drift gating, mirroring the task-card pipeline
(:mod:`chamber.tasks.render`).

A card states what the partner does in plain language, its stratum,
split, ``partner_id`` custody hash, construction provenance (registry
class + the committed parameter box, with exact values for public
members and the withheld marker for private ones), and the behavioural
fingerprint — so a reader can tell members apart without policy access
(ADR-018/I3; published hashes, withheld parameters).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from chamber.partners.sets import (
    PartnerMemberSpec,
    PartnerSetSpec,
    get_partner_set,
    list_partner_sets,
    parse_set_slug,
)

if TYPE_CHECKING:  # pragma: no cover
    from collections.abc import Mapping

_GENERATED_STAMP: str = (
    "<!-- Generated by scripts/render_partner_cards.py from chamber.partners.sets + the "
    "fingerprint archive — do not edit by hand. -->"
)

#: Plain-language behaviour blurbs per registry class (ADR-009 as amended:
#: a reader learns what the partner does, never its policy internals).
_CLASS_BLURBS: dict[str, str] = {
    "cocarry_impedance": (
        "A deterministic end-effector-space PI impedance controller for one "
        "co-carry arm (ADR-026 §Decision 1): it drives its bar-end toward the "
        "cooperative goal along a straight Cartesian path through a damped "
        "pseudo-inverse Jacobian, sharing the bar load compliantly with the "
        "ego arm. `kp`/`ki` set the Cartesian PI gains, `step_max` the "
        "per-step command clip (response speed), `damping` the pseudo-inverse "
        "regularisation, and `lag_steps` a bounded transport delay (a "
        "sluggish-but-competent member: delayed but convergent tracking)."
    ),
    "scripted_heuristic": (
        "The greedy planar-reach heuristic (ADR-009 §Consequences): a "
        "deterministic policy that steps toward its configured planar target "
        "(`target_x`/`target_y`) with a unit-clipped velocity command. On the "
        "Stage-1 pick-place control the ego solves the task alone; this "
        "member documents (does not manufacture) that partner-insensitivity."
    ),
    "handover_presenter": (
        "The frozen scripted presenter (ADR-026; Gate-0 rig): it hands the "
        "part into the shared workspace and lets go, binding the ego only "
        "through the presented initial condition. The grasp-pose error "
        "distribution (`grasp_pose_bias_deg`/`grasp_pose_sigma_deg`) is the "
        "coupling channel; lateral offset is success-side by construction "
        "and timing skew rides the takt budget."
    ),
    "frozen_cocarry_joint": (
        "A frozen jointly-trained MAPPO co-carry seat (ADR-011 §Decision as "
        "amended): the partner-side actor of a pair checkpoint, loaded with "
        "SHA-256 sidecar verification and run deterministic under no-grad "
        "(ADR-018/I3 black-box contract). It reads the symmetric full state "
        "(own + other proprioception, bar pose, goal) assembled from raw obs "
        "leaves — the same interface it trained on. Its cooperative style is "
        "whatever joint training produced with ITS ego; cross-play with any "
        "other ego is exactly the partner-familiarity question the zoo "
        "measures, and the fingerprint below characterises it behaviourally."
    ),
}


def archive_rel_dir(set_spec: PartnerSetSpec) -> str:
    """Repo-relative fingerprint-archive directory for a set (ADR-009 as amended)."""
    return f"spikes/results/partner-fingerprints/{set_spec.set_id}-v{set_spec.version}"


def cards_rel_dir(set_spec: PartnerSetSpec) -> str:
    """Cards directory name under ``docs/reference/partners/`` (ADR-027 §Consequences)."""
    return f"{set_spec.set_id}-v{set_spec.version}"


def _fmt(value: float) -> str:
    return f"{value:.4g}"


def _box_rows(member: PartnerMemberSpec) -> list[str]:
    if not member.param_box:
        return [
            "*(no parameter box — a learned member's behaviour is its frozen "
            "checkpoint; custody rides on the committed payload SHA-256 above)*"
        ]
    rows = ["| parameter | committed box | value |", "| --- | --- | --- |"]
    for key in sorted(member.param_box):
        edge = member.param_box[key]
        box = f"[{_fmt(edge.lo)}, {_fmt(edge.hi)}]" + (" (int)" if edge.kind == "int" else "")
        value = member.params[key] if member.params is not None else "*withheld*"
        rows.append(f"| `{key}` | {box} | {value} |")
    return rows


def _fingerprint_rows(fingerprint: Mapping[str, Any]) -> list[str]:
    rows = ["| statistic | value |", "| --- | --- |"]
    rows.extend(f"| `{key}` | {_fmt(float(fingerprint[key]))} |" for key in sorted(fingerprint))
    return rows


def render_member_card(
    set_spec: PartnerSetSpec,
    member: PartnerMemberSpec,
    member_payload: Mapping[str, Any],
) -> str:
    """Render one member card (ADR-009 as amended; ADR-018/I3).

    Args:
        set_spec: The registered set.
        member: The member under render.
        member_payload: The member's entry in the committed
            ``fingerprints.json`` (fingerprint + floor verdict).
    """
    blurb = _CLASS_BLURBS.get(
        member.registry_class,
        f"A `{member.registry_class}` partner (see the class docstring).",
    )
    if member.checkpoint_uri is not None:
        provenance_note = (
            "Learned member: behaviour lives in the frozen checkpoint "
            f"`{member.checkpoint_uri}` (committed payload SHA-256 "
            f"`{member.checkpoint_sha256}`; the loading wrapper re-verifies "
            "the ADR-002 sidecar). "
            + (f"**Provenance.** {member.provenance}" if member.provenance else "")
        )
    elif member.params is not None:
        provenance_note = (
            "Public member: the exact values below were drawn from the "
            "committed box under the maintainer-held derivation seed and are "
            "committed next to their digest."
        )
    else:
        provenance_note = (
            "Private member: the exact values are **withheld** (ADR-009 as "
            "amended — published hashes, withheld parameters). They were "
            "drawn from the committed box under the maintainer-held seed; "
            "the digest below verifies any authorised local re-derivation."
        )
    floor_line = (
        f"floor probe `{member_payload['floor_probe']}` — success "
        f"{_fmt(float(member_payload['floor_success']))} vs committed floor "
        f"{_fmt(set_spec.floor)} → "
        f"{'**PASS**' if member_payload['floor_pass'] else '**FAIL**'}"
    )
    lines = [
        f"# `{member.member_name}` — {set_spec.slug}",
        "",
        _GENERATED_STAMP,
        "",
        f"**Set.** `{set_spec.slug}` (task `{set_spec.task_id}@v{set_spec.task_version}`) · "
        f"**Stratum.** {'learned' if member.checkpoint_uri is not None else 'scripted'} · "
        f"**Split.** {member.split} · **Role.** {member.role}",
        "",
        f"**Identity.** `partner_id` `{member.partner_id}` · parameter digest "
        f"`{member.params_sha256}` · `weights_uri` `{member.weights_uri}`",
        "",
        "## What this partner does",
        "",
        blurb,
        "",
        "## Construction provenance",
        "",
        f"Built from registry class `{member.registry_class}` "
        f"(`PartnerSpec(seed={member.seed}, checkpoint_step={member.checkpoint_step})`). "
        + provenance_note,
        "",
        *_box_rows(member),
        "",
        "## Behavioural fingerprint",
        "",
        f"Committed probe suite: seeds {list(set_spec.probe_seeds)} x "
        f"{set_spec.probe_episodes_per_seed} episodes against the task's reference ego "
        f"(archive: `{archive_rel_dir(set_spec)}/{member.member_name}/`, an ADR-028 "
        "v3 bundle). Summary statistics of the member's action distribution and the "
        "dyad's stress channel — enough to tell members apart without policy access "
        "(ADR-018/I3).",
        "",
        *_fingerprint_rows(member_payload["fingerprint"]),
        "",
        f"**Competence floor.** {floor_line}",
        "",
    ]
    return "\n".join(lines)


def render_set_index(set_spec: PartnerSetSpec, payload: Mapping[str, Any]) -> str:
    """Render a set's roster index page (ADR-009 as amended; ADR-027 §Versioning)."""
    members_payload: Mapping[str, Any] = payload["members"]
    rows = [
        "| member | split | role | `partner_id` | floor success | fingerprint success |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for member in set_spec.members:
        entry = members_payload[member.member_name]
        rows.append(
            f"| [`{member.member_name}`]({member.member_name}.md) | {member.split} "
            f"| {member.role} | `{member.partner_id}` "
            f"| {_fmt(float(entry['floor_success']))} "
            f"| {_fmt(float(entry['fingerprint']['success_rate']))} |"
        )
    lines = [
        f"# Partner set `{set_spec.slug}`",
        "",
        _GENERATED_STAMP,
        "",
        f"Task: `{set_spec.task_id}@v{set_spec.task_version}` · members: "
        f"{len(set_spec.members)} ({len(set_spec.public_members)} public / "
        f"{len(set_spec.private_members)} private) · committed floor: "
        f"{_fmt(set_spec.floor)} on the `{set_spec.floor_probe}` probe.",
        "",
        set_spec.notes,
        "",
        "The public/private split is the deterministic ADR-009 rule — members "
        "ordered by `partner_id` hash, the first ⌈0.7·N⌉ public — recomputable "
        "from this roster; no hand-picking. Private members' behavioural "
        "parameters are withheld (published hashes, withheld parameters): they "
        "derive from the maintainer-held seed and verify against the committed "
        "digests. Set changes bump the version (ADR-027 §Versioning); frozen "
        "learned members join as a version bump.",
        "",
        *rows,
        "",
        f"Fingerprint archive: `{archive_rel_dir(set_spec)}/` "
        "(per-member ADR-028 v3 bundles + `fingerprints.json` + `SHA256SUMS.txt`).",
        "",
    ]
    return "\n".join(lines)


def render_partners_index(sets: list[PartnerSetSpec]) -> str:
    """Render the top-level partner-set index (ADR-009 as amended)."""
    rows = [
        "| set | task | members (public/private) | floor |",
        "| --- | --- | --- | --- |",
    ]
    rows.extend(
        f"| [`{spec.slug}`]({cards_rel_dir(spec)}/index.md) "
        f"| `{spec.task_id}@v{spec.task_version}` "
        f"| {len(spec.members)} ({len(spec.public_members)}/"
        f"{len(spec.private_members)}) | {_fmt(spec.floor)} |"
        for spec in sets
    )
    lines = [
        "# Partner sets",
        "",
        _GENERATED_STAMP,
        "",
        "Versioned per-task partner sets (ADR-009 §Decision as amended "
        "2026-07-05; ADR-027 §Versioning). Every member subclasses "
        "`PartnerBase` behind the `_FORBIDDEN_ATTRS` black-box shield "
        "(ADR-018/I3); cards publish identity hashes, construction boxes, and "
        "behavioural fingerprints — never private parameter values.",
        "",
        *rows,
        "",
    ]
    return "\n".join(lines)


def render_all_partner_cards(
    fingerprints_by_slug: Mapping[str, Mapping[str, Any]],
) -> dict[str, str]:
    """Render every card keyed by path relative to ``docs/reference/partners/`` (ADR-009; ADR-027).

    Args:
        fingerprints_by_slug: Committed ``fingerprints.json`` payloads
            keyed by set slug (the script loads them from the archive;
            a registered set with no committed archive is a loud
            ``KeyError`` — cards never render without evidence).
    """
    out: dict[str, str] = {}
    sets: list[PartnerSetSpec] = []
    for slug in list_partner_sets():
        set_id, version = parse_set_slug(slug)
        set_spec = get_partner_set(set_id, version=version)
        sets.append(set_spec)
        if slug not in fingerprints_by_slug:
            msg = (
                f"no fingerprint payload for set {slug!r}; generate + commit "
                f"{archive_rel_dir(set_spec)}/ first "
                "(scripts/generate_partner_fingerprints.py)"
            )
            raise KeyError(msg)
        payload = fingerprints_by_slug[slug]
        members_payload: Mapping[str, Any] = payload["members"]
        for member in set_spec.members:
            if member.member_name not in members_payload:
                msg = (
                    f"member {member.member_name!r} of {slug} has no entry in the "
                    "committed fingerprint archive — regenerate the archive"
                )
                raise KeyError(msg)
            out[f"{cards_rel_dir(set_spec)}/{member.member_name}.md"] = render_member_card(
                set_spec, member, members_payload[member.member_name]
            )
        out[f"{cards_rel_dir(set_spec)}/index.md"] = render_set_index(set_spec, payload)
    out["index.md"] = render_partners_index(sets)
    return out


__all__ = [
    "archive_rel_dir",
    "cards_rel_dir",
    "render_all_partner_cards",
    "render_member_card",
    "render_partners_index",
    "render_set_index",
]
