# SPDX-License-Identifier: Apache-2.0
"""Renderers for the generated benchmark-suite surfaces (ADR-027 §Consequences).

Renders the README task table and the ``docs/reference/tasks/`` cards
from the registry, so the public surfaces cannot drift from code. The
``scripts/render_task_table.py`` / ``scripts/render_task_cards.py``
wrappers do the file IO and the ``--check`` drift gating; keeping the
rendering here keeps :mod:`chamber.tasks` the single source of truth
(ADR-027 §Versioning) and the logic under the coverage gate.

All output is deterministic: tasks sort by ``(tier, task_id, version)``,
matching :func:`chamber.tasks.manifest`.
"""

from __future__ import annotations

from chamber.tasks.cards import card_prose
from chamber.tasks.registry import SUITE_NAME, SUITE_VERSION, get, list_registered
from chamber.tasks.spec import HETEROGENEITY_AXES, TaskSpec

#: Marker pair delimiting the generated README task table
#: (ADR-027 §Consequences — README drift gate).
README_TABLE_BEGIN: str = (
    "<!-- CHAMBER-BENCH-TASK-TABLE:BEGIN — generated by scripts/render_task_table.py; "
    "edit src/chamber/tasks/, not this table -->"
)
README_TABLE_END: str = "<!-- CHAMBER-BENCH-TASK-TABLE:END -->"

#: GitHub blob base for evidence links on the mkdocs site (card links
#: must resolve outside ``docs/``, ADR-027 §Consequences).
_GITHUB_BLOB_BASE: str = "https://github.com/fsafaei/concerto/blob/main"

_GENERATED_STAMP: str = (
    "<!-- Generated by scripts/render_task_cards.py from chamber.tasks — do not edit by hand. -->"
)

_TIER_NAMES: dict[int, str] = {
    0: "rig diagnostics",
    1: "controls",
    2: "admitted cooperation tasks",
    3: "documented candidates and closures",
}


def _sorted_specs() -> list[TaskSpec]:
    """Registered specs in manifest order (ADR-027 §Versioning)."""
    specs = [get(slug.split("@v")[0], int(slug.split("@v")[1])) for slug in list_registered()]
    return sorted(specs, key=lambda s: (s.tier, s.task_id, s.version))


def _axis_summary(spec: TaskSpec) -> str:
    """Compact non-``untested`` cell listing for the README table (ADR-027 §Validity matrix)."""
    marked = [
        f"{axis} `{spec.axes[axis]}`"
        for axis in HETEROGENEITY_AXES
        if spec.axes[axis] != "untested"
    ]
    return ", ".join(marked) if marked else "all untested"


def render_readme_table() -> str:
    """Render the README task/tier table, markers included (ADR-027 §Tier ladder).

    The table is the suite-composition view of :func:`chamber.tasks.manifest`;
    ``scripts/render_task_table.py --check`` fails CI when the committed
    README block differs from this render.
    """
    lines = [
        README_TABLE_BEGIN,
        "",
        "| Task | Tier | Status | Axis validity | Task card |",
        "|------|------|--------|---------------|-----------|",
    ]
    for spec in _sorted_specs():
        card = f"[{spec.task_id}](docs/reference/tasks/{spec.task_id}.md)"
        lines.append(
            f"| `{spec.slug}` — {spec.title} "
            f"| {spec.tier} ({_TIER_NAMES[spec.tier]}) "
            f"| {spec.admission_status} "
            f"| {_axis_summary(spec)} "
            f"| {card} |"
        )
    lines += [
        "",
        README_TABLE_END,
    ]
    return "\n".join(lines) + "\n"


def _evidence_link(path: str) -> str:
    return f"[`{path}`]({_GITHUB_BLOB_BASE}/{path})"


def render_task_card(spec: TaskSpec) -> str:
    """Render one ``docs/reference/tasks/<task_id>.md`` card (ADR-027 §Consequences)."""
    prose = card_prose(spec.task_id)
    adr_027 = _evidence_link("adr/ADR-027-chamber-bench-v1-protocol.md")
    header_cells = " | ".join(HETEROGENEITY_AXES)
    status_cells = " | ".join(f"`{spec.axes[axis]}`" for axis in HETEROGENEITY_AXES)
    stress = (
        spec.stress_channel
        if spec.stress_channel is not None
        else "None — no force coupling channel."
    )
    lines = [
        _GENERATED_STAMP,
        "",
        f"# `{spec.slug}` — {spec.title}",
        "",
        prose.description,
        "",
        f"**Tier {spec.tier} — {_TIER_NAMES[spec.tier]}** · **Status: {spec.admission_status}** · "
        f"Suite: {SUITE_NAME} v{SUITE_VERSION} ({adr_027})",
        "",
        "## Spaces",
        "",
        f"- **Action space.** {spec.action_space_summary}.",
        f"- **Observation.** {spec.observation_summary}.",
        f"- **Simulator backend.** `{spec.sim_backend}` · **Agents.** {spec.n_agents}",
        "",
        "## Stress channel",
        "",
        stress,
        "",
        "## Axis validity",
        "",
        f"Per-cell status under the validity matrix ({adr_027}):",
        "",
        f"| {header_cells} |",
        f"|{'---|' * len(HETEROGENEITY_AXES)}",
        f"| {status_cells} |",
        "",
        "## Industrial analogue",
        "",
        prose.industrial_analogue,
    ]
    if prose.falsifier is not None:
        lines += ["", "## Committed falsifier", "", prose.falsifier]
    if prose.open_challenge is not None:
        lines += ["", "## Open challenge", "", prose.open_challenge]
    lines += [
        "",
        "## Evidence",
        "",
        *[f"- {_evidence_link(path)}" for path in spec.evidence],
        "",
        "## How to run one episode",
        "",
        "```python",
        prose.run_snippet.rstrip("\n"),
        "```",
    ]
    if spec.notes:
        lines += ["", "## Notes", "", spec.notes]
    return "\n".join(lines) + "\n"


def render_cards_index() -> str:
    """Render ``docs/reference/tasks/index.md`` — the suite overview page (ADR-027 §Tier ladder)."""
    lines = [
        _GENERATED_STAMP,
        "",
        f"# {SUITE_NAME} v{SUITE_VERSION} task cards",
        "",
        "One card per task version in the pinned suite composition. The",
        "registry (`chamber.tasks`) is the single source of truth; these",
        "pages and the README task table render from it "
        f"({_evidence_link('adr/ADR-027-chamber-bench-v1-protocol.md')}).",
        "",
        "Emit the machine-readable manifest with:",
        "",
        "```console",
        "$ chamber-eval manifest",
        "```",
        "",
        "| Task | Tier | Status |",
        "|------|------|--------|",
    ]
    lines.extend(
        f"| [`{spec.slug}` — {spec.title}]({spec.task_id}.md) "
        f"| {spec.tier} ({_TIER_NAMES[spec.tier]}) "
        f"| {spec.admission_status} |"
        for spec in _sorted_specs()
    )
    return "\n".join(lines) + "\n"


def render_all_cards() -> dict[str, str]:
    """Render every card plus the index, keyed by file name (ADR-027 §Consequences).

    Keys are file names under ``docs/reference/tasks/`` (e.g.
    ``cocarry.md``, ``index.md``); values are the full file contents.
    ``scripts/render_task_cards.py --check`` fails when the committed
    directory differs from this render in content **or membership**.
    """
    files = {f"{spec.task_id}.md": render_task_card(spec) for spec in _sorted_specs()}
    files["index.md"] = render_cards_index()
    return files


__all__ = [
    "README_TABLE_BEGIN",
    "README_TABLE_END",
    "render_all_cards",
    "render_cards_index",
    "render_readme_table",
    "render_task_card",
]
