#!/usr/bin/env bash
# Block AI-tooling leaks before commit / push (plan/10 §3.3 + §3.10).
#
# Used as:
#   - a pre-commit + pre-push local hook (wired in .pre-commit-config.yaml)
#   - the make verify-no-ai-mentions target
#
# All four greps must come back empty for the script to exit 0.
# Exempt: this file itself (the regex literal lives here by necessity).

set -euo pipefail

PATTERN='claude|anthropic|cowork|generated by ai|co-authored-by:[[:space:]]*(claude|anthropic)'

# Files that are EXPECTED to mention these strings (for legitimate reasons)
# and must therefore be exempted from this check. Keep this list short and
# justify every entry. New entries require an ADR amendment.
#   - scripts/check_no_ai_mentions.sh : the regex literal lives here.
#   - .gitignore                      : the entries that gitignore CLAUDE.md, .claude/, etc.
EXEMPT_REGEX='^(scripts/check_no_ai_mentions\.sh|\.gitignore)$'

fail=0

# 1. Staged diff (pre-commit context). If staged is empty, this is a no-op.
# Strip out additions in exempt files so an edit to .gitignore doesn't trip.
if git diff --cached -U0 -- ':(exclude)scripts/check_no_ai_mentions.sh' ':(exclude).gitignore' 2>/dev/null \
   | grep -Eni "$PATTERN" >/dev/null; then
  echo "[hygiene] AI-tooling mention in staged diff. Aborting." >&2
  fail=1
fi

# 2. Tracked files in the working tree (catches anything already in the index).
if git ls-files | xargs -r grep -lEni "$PATTERN" 2>/dev/null \
   | grep -vE "$EXEMPT_REGEX" \
   | grep -E '.' >/dev/null; then
  echo "[hygiene] AI-tooling mention in tracked files. Aborting." >&2
  git ls-files | xargs -r grep -lEni "$PATTERN" 2>/dev/null \
    | grep -vE "$EXEMPT_REGEX" >&2
  fail=1
fi

# 3. Commit history (catches authored trailers across all branches).
if git log --all --pretty=format:'%h %s%n%b' \
   | grep -Eni "$PATTERN" >/dev/null; then
  echo "[hygiene] AI-tooling mention in commit history. Aborting." >&2
  fail=1
fi

# 4. Untracked-but-not-ignored files (catches new files written outside the gitignore).
LEAKED_UNTRACKED=$(git ls-files --others --exclude-standard \
  | xargs -r grep -lEni "$PATTERN" 2>/dev/null \
  | grep -vE "$EXEMPT_REGEX" || true)
if [[ -n "$LEAKED_UNTRACKED" ]]; then
  echo "[hygiene] AI-tooling mention in untracked-but-not-ignored files. Aborting." >&2
  echo "[hygiene] Offending paths:" >&2
  echo "$LEAKED_UNTRACKED" | sed 's/^/    /' >&2
  echo "[hygiene] Either add each path to .gitignore (if it's a local artefact)" >&2
  echo "[hygiene] or delete it. Then re-run." >&2
  fail=1
fi

exit "$fail"
