#!/usr/bin/env bash
# Block AI-tooling leaks before commit / push (plan/10 §3.3 + §3.10).
#
# Used as:
#   - a pre-commit + pre-push local hook (wired in .pre-commit-config.yaml)
#   - the make verify-no-ai-mentions target
#
# All four greps must come back empty for the script to exit 0.
# Exempt: this file itself (the regex literal lives here by necessity).

set -euo pipefail

PATTERN='claude|anthropic|cowork|generated by ai|co-authored-by:[[:space:]]*(claude|anthropic)'
SELF_RELATIVE_PATH='scripts/check_no_ai_mentions.sh'

fail=0

# 1. Staged diff (pre-commit context). If staged is empty, this is a no-op.
if git diff --cached -U0 2>/dev/null | grep -Eni "$PATTERN" >/dev/null; then
  echo "[hygiene] AI-tooling mention in staged diff. Aborting." >&2
  fail=1
fi

# 2. Tracked files in the working tree (catches anything already in the index).
if git ls-files | xargs -r grep -lEni "$PATTERN" 2>/dev/null \
   | grep -v "^${SELF_RELATIVE_PATH}\$" \
   | grep -E '.' >/dev/null; then
  echo "[hygiene] AI-tooling mention in tracked files. Aborting." >&2
  git ls-files | xargs -r grep -lEni "$PATTERN" 2>/dev/null \
    | grep -v "^${SELF_RELATIVE_PATH}\$" >&2
  fail=1
fi

# 3. Commit history (catches authored trailers across all branches).
if git log --all --pretty=format:'%h %s%n%b' \
   | grep -Eni "$PATTERN" >/dev/null; then
  echo "[hygiene] AI-tooling mention in commit history. Aborting." >&2
  fail=1
fi

# 4. Untracked-but-not-ignored files (catches new files Claude wrote that you forgot to add or gitignore).
if git ls-files --others --exclude-standard \
   | xargs -r grep -lEni "$PATTERN" 2>/dev/null >/dev/null; then
  echo "[hygiene] AI-tooling mention in untracked-but-not-ignored files. Aborting." >&2
  fail=1
fi

exit "$fail"
