name: Docs Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb  # v5.4.1
        with:
          python-version: "3.11"
      - run: uv sync --extra docs --group dev
      - run: git config user.name "Farhad Safaei"
      - run: git config user.email "safaei.farhad@gmail.com"
      - run: uv run mike deploy --push --update-aliases dev latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
